/**
 * The HX-5 fixtures — the recorded run Phase 5 replays offline (FE-10).
 *
 * One `run.json` covering all four window outcomes, and one focused file per
 * outcome, because TS-5 asserts the theater reaches the correct terminal
 * render for a settled, a rolled, an evicted and a rolled-back window and a
 * failing e2e is easier to read when the fixture is only about that.
 *
 * **Provenance.** `dex-scenario.sh --record` regenerates these from a real
 * enclave run: it writes the observation log the enclave produced and folds it
 * with the same recorder. What is committed here is generated by the
 * settlement oracle instead, so the numbers are the ones the contracts would
 * produce and the fixtures exist before an enclave is available to any
 * particular reader. `fixtures/README.md` says which of the two the files on
 * disk came from.
 */

import { writeFileSync } from "node:fs";

import { TRADERS } from "./accounts.ts";
import type { BookParams } from "./book.ts";
import { Q96, fromBig, mulDiv, spotPriceX96 } from "./math.ts";
import { formatObservationLog } from "./observation.ts";
import type { Observation } from "./observation.ts";
import { sqrtPriceForPrice } from "./pool.ts";
import type { Pool } from "./pool.ts";
import { record } from "./record.ts";
import { Simulation } from "./simulate.ts";
import type { GasModel } from "./simulate.ts";
import { validate } from "./validate.ts";
import type { Side } from "../../indexer/schema/index.ts";

const ONE = 10n ** 18n;

/** The launch configuration the scenario runs (EC-1). */
export const FIXTURE_PARAMS: BookParams = {
  feeMode: "bps",
  feeBps: 1n,
  feeFixedA: 0n,
  feeFixedB: 0n,
  routeFeeModel: "absorb",
  routeFeeWei: 0n,
  assetAIsNative: true,
};

/**
 * The devnet's gas, and ER-2's ~400k-gas retail swap as the counterfactual
 * (IX-3). The absolute numbers are the devnet's, not mainnet's; what the
 * fixture carries is the *shape* of the amortisation, and TS-2's recorded gas
 * is what feeds EC-1's fee ceiling.
 */
export const FIXTURE_GAS: GasModel = {
  base: 210_000n,
  perFill: 9_000n,
  priceWei: 1_000_000_000n,
  directSwap: 400_000n,
};

/**
 * A pool deep enough that eight orders move it by basis points, not percent,
 * at the 0.05% fee tier — the deepest mainnet ETH pool's, and the one ER-2's
 * density baseline is measured against. The tier matters to every limit in
 * this file: a residual-side order can never be filled inside a tolerance
 * tighter than the fee the swap pays, so 5 bps of fee is what makes a 20 bps
 * tolerance a real limit rather than an impossible one.
 */
export function fixturePool(price: bigint, liquidity = 2_000_000n * ONE): Pool {
  return { sqrtPriceX96: sqrtPriceForPrice(price, 1n), liquidity, fee: 500n };
}

/**
 * A limit `toleranceBps` worse than the price the order was quoted at, net of
 * the fee — the shape A.6's happy path asks for ("limits at the mirror price ±
 * tolerance").
 */
function limitAt(side: Side, sellAmount: bigint, priceX96: bigint, toleranceBps: bigint): bigint {
  const netIn = sellAmount - sellAmount / 10_000n;
  const atPrice = side === "SELL_A_FOR_B" ? mulDiv(netIn, priceX96, Q96) : mulDiv(netIn, Q96, priceX96);
  return mulDiv(atPrice, 10_000n - toleranceBps, 10_000n);
}

function newSimulation(pool: Pool): Simulation {
  return new Simulation({
    profile: "full",
    params: FIXTURE_PARAMS,
    pool,
    // A fixed wall clock, so the fixture is byte-identical between runs and a
    // diff on it is a real change rather than today's date.
    startUnix: 1_788_000_000,
    startL1Block: 1_000,
    startL2Block: 1,
    windowSlots: 1,
    gas: FIXTURE_GAS,
  });
}

/**
 * A.6's happy path: a mix of buys and sells from eight accounts across five L2
 * blocks, limits at the mirror price plus a tolerance, settled at the Sync
 * block. Every one of the eight fills, which is what makes
 * `fills_per_settlement == 8` an assertion rather than a hope.
 */
function placeTheEight(simulation: Simulation, priceX96: bigint): void {
  const sizes: readonly bigint[] = [3n, 5n, 2n, 4n];
  const traders = TRADERS;
  for (let i = 0; i < 8; i += 1) {
    const trader = traders[i % traders.length];
    if (trader === undefined) throw new Error("the fixture needs eight trader accounts");
    const sellsA = i % 2 === 0;
    const side: Side = sellsA ? "SELL_A_FOR_B" : "SELL_B_FOR_A";
    const scale = sizes[Math.floor(i / 2) % sizes.length] ?? 1n;
    const sellAmount = sellsA ? scale * ONE : scale * 3000n * ONE;
    // Tolerances spread from 20 to 55 bps — above the pool's 5 bps fee, so
    // every one of the eight is fillable at the mirror price, and spread, so a
    // later drift excludes some and not others.
    const tolerance = 20n + BigInt(i) * 5n;
    simulation.place(trader, side, sellAmount, limitAt(side, sellAmount, priceX96, tolerance));
    if (i % 2 === 1) simulation.block();
  }
  simulation.blocks(2);
}

/** The whole run: a settled window, a rolled one, an eviction, a rollback. */
export function fixtureObservations(): Observation[] {
  const pool = fixturePool(3000n);
  const simulation = newSimulation(pool);
  const priceX96 = spotPriceX96(pool.sqrtPriceX96);

  // Window 0 — the happy path: eight orders, one settlement, eight fills.
  placeTheEight(simulation, priceX96);
  simulation.settle();

  // Window 1 — mid-window drift beyond some limits: the orders inside their
  // limit fill, the rest stay open and roll (FL-8, EC-2).
  const drifted = fixturePool(2960n);
  for (let i = 0; i < 6; i += 1) {
    const trader = TRADERS[i];
    if (trader === undefined) continue;
    const side: Side = i % 2 === 0 ? "SELL_A_FOR_B" : "SELL_B_FOR_A";
    const sellAmount = side === "SELL_A_FOR_B" ? 2n * ONE : 6000n * ONE;
    simulation.place(trader, side, sellAmount, limitAt(side, sellAmount, priceX96, 18n + BigInt(i) * 6n));
    if (i % 2 === 1) simulation.block();
  }
  simulation.drift({ ...simulation.currentPool(), sqrtPriceX96: drifted.sqrtPriceX96 });
  simulation.blocks(2);
  simulation.settle();

  // The price comes back, so the orders that rolled are fillable again — a
  // window with nothing settleable would produce no settlement at all, and the
  // two failures below are about settlements that were sent.
  simulation.drift({ ...simulation.currentPool(), sqrtPriceX96: fixturePool(3000n).sqrtPriceX96 });

  // Window 2 — poison eviction: the composed transaction would revert, so
  // there is no L1 transaction, no gas, and the window stays open (FL-7).
  simulation.blocks(3);
  simulation.settle({ kind: "evicted", reason: "ExecutionPriceOutsideBand" });

  // The same window again — this time the bundle lands and is then skipped at
  // `postBatch`: a rollback, not an eviction, and the one that spent L1 gas
  // (SV-4).
  simulation.blocks(3);
  simulation.settle({ kind: "rolled_back", cause: "postbatch_skip" });

  // And once more, repaired: the window re-formed and settled (A.4).
  simulation.blocks(3);
  simulation.settle();

  // A last window left open, so a reader sees the stream continue rather than
  // stop on a terminal state.
  simulation.blocks(4);
  return simulation.observations;
}

/** One focused run per A.4 outcome, for TS-5's four terminal renders. */
export function focusedObservations(): Record<string, Observation[]> {
  const price = spotPriceX96(fixturePool(3000n).sqrtPriceX96);

  const settled = newSimulation(fixturePool(3000n));
  placeTheEight(settled, price);
  settled.settle();
  settled.blocks(2);

  const rolled = newSimulation(fixturePool(3000n));
  placeTheEight(rolled, price);
  rolled.drift({ ...rolled.currentPool(), sqrtPriceX96: fixturePool(2955n).sqrtPriceX96 });
  rolled.settle();
  rolled.blocks(2);

  const evicted = newSimulation(fixturePool(3000n));
  placeTheEight(evicted, price);
  evicted.settle({ kind: "evicted", reason: "ReferencePriceOutsideBand" });
  evicted.blocks(2);

  const rolledBack = newSimulation(fixturePool(3000n));
  placeTheEight(rolledBack, price);
  rolledBack.settle({ kind: "rolled_back", cause: "postbatch_skip" });
  rolledBack.blocks(2);

  return {
    settled: settled.observations,
    rolled: rolled.observations,
    evicted: evicted.observations,
    "rolled-back": rolledBack.observations,
  };
}

/** Writes every fixture, validating each against the frozen schema first. */
export function writeFixtures(directory: string, observations: readonly Observation[]): string[] {
  const written: string[] = [];

  const run = validate(record(observations).events);
  writeFileSync(`${directory}/run.json`, `${JSON.stringify(run, null, 2)}\n`);
  written.push(`${directory}/run.json: ${run.length} events`);

  for (const [name, focused] of Object.entries(focusedObservations())) {
    const events = validate(record(focused).events);
    writeFileSync(`${directory}/${name}.json`, `${JSON.stringify(events, null, 2)}\n`);
    writeFileSync(`${directory}/${name}.observations.jsonl`, formatObservationLog(focused));
    written.push(`${directory}/${name}.json: ${events.length} events`);
  }

  return written;
}

/** The fixture's own summary, for a run report. */
export function fixtureSummary(observations: readonly Observation[]): string {
  const events = record(observations).events;
  const kinds = new Map<string, number>();
  for (const event of events) kinds.set(event.kind, (kinds.get(event.kind) ?? 0) + 1);
  return [...kinds.entries()].map(([kind, count]) => `${kind}=${count}`).join(" ");
}

/** `fromBig` is re-exported so a fixture script can print amounts unchanged. */
export { fromBig };
