#!/usr/bin/env bash
# Generate every framework reference in the repository from FRAMEWORK_COMMIT (RL-1).
#
#   scripts/framework-pin.sh          write the generated files
#   scripts/framework-pin.sh --check  fail if any generated file has drifted
#
# The pin has exactly three consumers. Each is written whole by this script and
# carries a "generated" header, so a hand edit is caught by --check.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PIN="$ROOT/FRAMEWORK_COMMIT"
CHECK=0
[[ "${1:-}" == "--check" ]] && CHECK=1

# FRAMEWORK_COMMIT is KEY=value with # comments; values may contain spaces.
pin() {
    local key="$1" value
    value="$(sed -n "s/^${key}=//p" "$PIN" | head -1)"
    if [[ -z "$value" ]]; then
        echo "framework-pin: $key missing from FRAMEWORK_COMMIT" >&2
        exit 1
    fi
    printf '%s' "$value"
}

ROLLUP0_REPO="$(pin EEZ_ROLLUP0_REPO)"
ROLLUP0_COMMIT="$(pin EEZ_ROLLUP0_COMMIT)"
PROTOCOL_REV="$(pin EEZ_CORE_PROTOCOL_REV)"
PROTOCOL_TAG="$(pin EEZ_CORE_PROTOCOL_TAG)"
KURTOSIS_PACKAGE="$(pin KURTOSIS_PACKAGE)"
SETTLER_CRATES="$(pin SETTLER_FRAMEWORK_CRATES)"

HEADER="Generated by scripts/framework-pin.sh from FRAMEWORK_COMMIT — do not edit."

# emit <path> < content-on-stdin
emit() {
    local target="$ROOT/$1" tmp
    tmp="$(mktemp)"
    cat >"$tmp"
    if [[ $CHECK -eq 1 ]]; then
        if ! diff -u "$target" "$tmp" >/dev/null 2>&1; then
            echo "framework-pin: $1 is out of date with FRAMEWORK_COMMIT; run 'make pin'" >&2
            diff -u "$target" "$tmp" >&2 || true
            rm -f "$tmp"
            exit 1
        fi
        rm -f "$tmp"
    else
        mkdir -p "$(dirname "$target")"
        mv "$tmp" "$target"
        echo "framework-pin: wrote $1"
    fi
}

# 1. Foundry remapping — to the pinned eez-core-protocol source, never to
#    eez-rollup0's devnet contracts/ (RL-1).
# remappings.txt has no comment syntax, so the provenance lives in
# FRAMEWORK_COMMIT and foundry.toml's header; --check is what keeps this file
# honest. The revision is EEZ_CORE_PROTOCOL_REV and the repository is
# EEZ_CORE_PROTOCOL_REPO, both in FRAMEWORK_COMMIT and in .gitmodules.
emit contracts/remappings.txt <<EOF
eez-core-protocol/=lib/eez-core-protocol/src/
forge-std/=lib/forge-std/src/
@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/
EOF

# 2. Cargo git+rev dependency on the node's RPC and signing crates. Included by
#    the settler manifest when WP-3 wires the framework in; the scaffold's
#    stubs depend on nothing so `cargo test` stays offline and fast.
{
    echo "# $HEADER"
    echo "# eez-rollup0 @ $ROLLUP0_COMMIT"
    echo "[dependencies]"
    # SETTLER_FRAMEWORK_CRATES is a space-separated list; splitting is the point.
    # shellcheck disable=SC2086
    for crate in $SETTLER_CRATES; do
        echo "$crate = { git = \"$ROLLUP0_REPO\", rev = \"$ROLLUP0_COMMIT\" }"
    done
} | emit settler/framework-deps.toml

# 3. Kurtosis package reference for the enclave scenario (UP-3).
emit scenario/framework-pin.env <<EOF
# $HEADER
EEZ_ROLLUP0_REPO=$ROLLUP0_REPO
EEZ_ROLLUP0_COMMIT=$ROLLUP0_COMMIT
EEZ_KURTOSIS_PACKAGE=$KURTOSIS_PACKAGE
EEZ_KURTOSIS_LOCATOR=$KURTOSIS_PACKAGE@$ROLLUP0_COMMIT
EOF

# The submodule gitlink is a fourth place the protocol revision is written; it
# is git's own storage, not a generated file, so --check compares rather than
# rewrites it.
SUBMODULE="$ROOT/contracts/lib/eez-core-protocol"
if [[ -e "$SUBMODULE" ]]; then
    ACTUAL="$(git -C "$ROOT" ls-tree HEAD contracts/lib/eez-core-protocol | awk '{print $3}')"
    if [[ -n "$ACTUAL" && "$ACTUAL" != "$PROTOCOL_REV" ]]; then
        echo "framework-pin: contracts/lib/eez-core-protocol is at $ACTUAL, FRAMEWORK_COMMIT says $PROTOCOL_REV" >&2
        echo "framework-pin: check the submodule out at $PROTOCOL_REV and commit the gitlink" >&2
        exit 1
    fi
fi

SUMMARY="eez-rollup0 @ ${ROLLUP0_COMMIT:0:9}, eez-core-protocol @ ${PROTOCOL_REV:0:9} ($PROTOCOL_TAG)"
if [[ $CHECK -eq 1 ]]; then
    echo "framework-pin: every generated reference matches FRAMEWORK_COMMIT — $SUMMARY"
else
    echo "framework-pin: pinned to $SUMMARY"
fi
